feat: check ssh key

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -121,13 +121,24 @@ jobs:
         uses: actions/setup-node@v3
         with:
           node-version: '16'
+      
+      - name: Setup SSH Key
+        run: |
+          echo "${{ secrets.EC2_SSH_KEY }}" > id_rsa
+          chmod 600 id_rsa
+      
+      - name: Check if SSH key was written correctly
+        run: |
+          echo "Checking key file..."
+          test -f id_rsa && echo "Key file exists" || echo "Missing key file"
+          test -s id_rsa && echo "Key file has content" || echo "Key file is empty"
 
       - name: SSH into EC2 instance and deploy
         uses: appleboy/ssh-action@master
         with:
           host: ec2-18-204-209-146.compute-1.amazonaws.com
           username: ec2-user
-          key: ${{ secrets.MY_EC2_SSH_KEY }}
+          key: ./id_rsa
           script: |
             sudo docker pull llab/network-nextapp:latest
             sudo docker pull llab/network-socket:latest
